# Generated by Django 4.1.5 on 2023-04-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_searches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='searches_left',
            field=models.IntegerField(default=0),
        ),
    ]
