# Generated by Django 4.1.5 on 2023-04-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cusines',
            old_name='cusine',
            new_name='usine',
        ),
    ]
