# Generated by Django 4.1.5 on 2023-04-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_rename_cusine_cusines_usine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cusines',
            old_name='usine',
            new_name='cusine',
        ),
    ]
