# Generated by Django 4.1.5 on 2023-05-06 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_rename_usine_cusines_cusine'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciepes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
