# Generated by Django 4.1.5 on 2023-05-30 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_trend_container_trending_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend_container',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=99999999999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trend_container',
            name='item',
            field=models.CharField(default=django.utils.timezone.now, max_length=99999999),
            preserve_default=False,
        ),
    ]
